export const GET_ALL_BIRDS = 'GET_ALL_BIRDS';
export const GET_ALL_ANIMALS = 'GET_ALL_ANIMALS';
export const GET_ALL_REPTILES = 'GET_ALL_REPTILES';
export const GET_SPECIES_DETAILS_BY_ID = 'GET_SPECIES_DETAILS_BY_ID';
export const RESET_SPECIES_DETAIL = 'RESET_SPECIES_DETAIL';
export const RESET_REPTILES = 'RESET_REPTILES';
export const RESET_BIRDS = 'RESET_BIRDS';
export const RESET_ANIMALS = 'RESET_ANIMALS';